### PR TITLE
New maintainer.

### PR DESCRIPTION
**Pull request by hlef**
Hi,
I've made some changes in d/changelog, d/control and d/copyright. I've tried to build the package, and it builds fine. The resulting package seems also to be lintian clear. 

Regards,
 Hugo

### CODE REVIEW

**Comment by porridge** [comment]
Please also change the Vcs-\* fields to point at your repository.

**Comment by hlef** [comment]
Done. ;)

**Comment by porridge** [comment]
OK, I can see the Vcs-\* changes now that I reloaded the page :-)
But please do an interactive rebase to squash the unnecessary commits and .pc/ changes.

**Comment by hlef** [comment]
It seems also to be good now.

**Comment by hlef** [comment]
The directory appeared to be dirty, so, I've deleted it and done again the changes. :) 
I've made an other pull request. :)

**Comment by porridge** [comment]
Added a note to README about your repo being the new canonical place, and I'm about to archive this repo, so closing open PRs in advance...

**Pull request closed without merging**
